import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import type { Book, BookResponse } from "@/api/types";
import { getBooks } from "@/api/handlers";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [books, setBooks] = useState<Array<Book>>([]);
    const [page, setPage] = useState<number>(1);
    const [pageData, setPageData] = useState(null);

    useEffect(() => {
        getBooks(page).then((data: BookResponse) => {
            const {results, ...rest} = data;
            setBooks(data.results);
            setPageData(rest)
        });
    }, [page]);

    return (
        <>
            <Head>
                <title>Library</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div className="header">Library</div>
                <div className={styles.section}>
                    <div className={styles.list}>
                        {books.map((book) => (
                            <div className={styles.item} key={book.BookID}>
                                <div className={styles.itemLabel}>
                                    {book.BookName}
                                </div>
                                <div className={styles.itemQty}>
                                    {book.NumberOfCopies}
                                </div>
                                <div className="cta">
                                    <button type="button" onClick={() => false}>
                                        Checkout
                                    </button>
                                    <button type="button" onClick={() => false}>
                                        Return
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </main>
        </>
    );
}
